version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pocuser
      POSTGRES_PASSWORD: pocpass
      POSTGRES_DB: pocdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://pocuser:pocpass@db:5432/pocdb
    ports:
      - "8000:8000"
    restart: always
volumes:
  pgdata:
